# -*- coding: utf-8 -*-
"""homework-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wO3kjpsbF-6BAsMFf3mrhxPTLmkK0Gmh

# Семинар: токенайзеры, размеры тензоров и attention

В этом ноутбуке три части:

1. **Токенайзеры**: сравниваем разные токенайзеры из `transformers` на английском, русском, китайском и коде.
2. **Перемножение тензоров**: учимся следить за размерами в линейных слоях и батчах.
3. **Attention**: смотрим параметры модели, предсказываем размеры тензоров и визуализируем attention.

## 0. Установка и импорты
"""

# Если чего-то не хватает, раскомментируйте:
# !pip install -q transformers sentencepiece matplotlib torch

import math
import random
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

from transformers import (
    AutoTokenizer,
    AutoConfig,
    AutoModel,
    AutoModelForCausalLM,
    AutoModelForSeq2SeqLM,
)

torch.manual_seed(42)
np.random.seed(42)
random.seed(42)

"""# 1. Токенайзеры

Будем смотреть, как разные токенайзеры режут:
- английский,
- русский,
- китайский,
- код.

Важно: один и тот же текст может разбиваться очень по-разному. Это зависит от:
- алгоритма токенизации,
- словаря,
- языков, на которых обучали токенайзер,
- того, использует ли он byte-level BPE, SentencePiece и т.д.

"""

texts = {
    'english': 'The small dog sleeps on the carpet.',
    'russian': 'Маленькая собака спит на коврике.',
    'chinese': '小狗睡在地毯上。',
    'code': 'def attention(q, k, v):\n    return softmax(q @ k.T) @ v',
}

tokenizer_names = {
    'bert-base-uncased': 'BERT WordPiece',
    'gpt2': 'GPT-2 byte-level BPE',
    'google/mt5-small': 'mT5 SentencePiece',
    'xlm-roberta-base': 'XLM-R SentencePiece',
}

def inspect_tokenizer(tok_name, text):
    tok = AutoTokenizer.from_pretrained(tok_name)
    encoded = tok(text, return_tensors='pt')
    tokens = tok.convert_ids_to_tokens(encoded['input_ids'][0])
    print(f'=== {tok_name} ===')
    print('Text:   ', repr(text))
    print('Tokens: ', tokens)
    print('N toks: ', len(tokens))
    print("vocab_size:", tok.vocab_size)
    print("full_vocab_size:", len(tok.get_vocab()))
    print()

for tok_name in tokenizer_names:
    for lang, text in texts.items():
        inspect_tokenizer(tok_name, text)

"""## 1.1. Более аккуратное сравнение

Сделаем таблицу числа токенов для разных текстов и токенайзеров.
"""

rows = []
for tok_name, tok_descr in tokenizer_names.items():
    tok = AutoTokenizer.from_pretrained(tok_name)
    row = {'tokenizer': tok_descr}
    for lang, text in texts.items():
        n = len(tok(text)['input_ids'])
        row[lang] = n
    rows.append(row)

for row in rows:
    print(row)

"""## 1.2. Вопросы для обсуждения

1. Почему один и тот же русский текст у разных токенайзеров дает разное число токенов?
2. Почему код часто режется иначе, чем обычный текст?
3. Почему для multilingual-моделей токенизация русского обычно лучше, чем у чисто английских моделей?
4. Почему byte-level токенизаторы иногда выглядят странно на не-английских языках?

# 2. Перемножение тензоров и размеры

Главный навык: **всегда подписывать размеры**.

Полезное правило:
- если умножаем `A @ B`, то внутренняя размерность должна совпадать;
- если `A` имеет форму `(m, n)`, а `B` форму `(n, k)`, то результат имеет форму `(m, k)`.

Для нейросетей обычно встречаются такие случаи:
- матрица на вектор,
- матрица на матрицу,
- линейный слой,
- батч объектов,
- батч последовательностей.

## 2.1. Матрица на вектор
"""

W = torch.randn(3, 5)   # (out_dim, in_dim)
x = torch.randn(5)      # (in_dim,)

y = W @ x

print('W.shape =', W.shape)
print('x.shape =', x.shape)
print('y.shape =', y.shape)

"""Здесь:
- `W \in R^{3 x 5}`
- `x \in R^{5}`
- значит `y \in R^{3}`

## 2.2. Linear layer

В `PyTorch` линейный слой хранит веса формы `(out_features, in_features)`.

То есть если `Linear(5, 3)`, то:
- вход имеет последнюю размерность 5,
- выход имеет последнюю размерность 3.
"""

lin = nn.Linear(5, 3)
x = torch.randn(5)
y = lin(x)

print('lin.weight.shape =', lin.weight.shape)
print('lin.bias.shape   =', lin.bias.shape)
print('x.shape          =', x.shape)
print('y.shape          =', y.shape)

"""## 2.3. Батч объектов"""

lin = nn.Linear(5, 3)
x = torch.randn(4, 5)   # batch_size = 4, feature_dim = 5
y = lin(x)

print('x.shape =', x.shape)
print('y.shape =', y.shape)

"""Правило: `Linear` действует по **последней размерности**, а все предыдущие размерности считаются батчевыми.

## 2.4. Батч последовательностей

Частый случай в NLP:
- `batch_size = B`
- `seq_len = T`
- `hidden_dim = d`

Тогда тензор скрытых состояний имеет форму:

\[
(B, T, d)
\]
"""

B, T, d_in, d_out = 2, 4, 5, 3
x = torch.randn(B, T, d_in)
lin = nn.Linear(d_in, d_out)
y = lin(x)

print('x.shape =', x.shape)
print('y.shape =', y.shape)

"""## 2.5. Упражнения на размеры

Попробуйте сначала **предсказать размер**, а потом выполнить код.
"""

# Упражнение 1
A = torch.randn(7, 11)
x = torch.randn(11)
y = A @ x
print('Exercise 1:', y.shape)

# Упражнение 2
A = torch.randn(8, 6)
B = torch.randn(6, 10)
C = A @ B
print('Exercise 2:', C.shape)

# Упражнение 3
x = torch.randn(3, 12, 64)
lin = nn.Linear(64, 128)
y = lin(x)
print('Exercise 3:', y.shape)

# Упражнение 4
x = torch.randn(2, 5, 4)
W = torch.randn(4, 7)
y = x @ W
print('Exercise 4:', y.shape)

"""## 2.6. Как следить за размерами

Хорошая стратегия:

1. **Подписать смысл каждой оси**.
   Например: `(batch, seq, hidden)`.

2. **Подписать размеры до операции**.
   Например: `Q: (B, T, d_k)`, `K: (B, T, d_k)`.

3. **Понять, какие оси участвуют в умножении**.

4. **После операции снова подписать смысл осей**.

В attention это особенно важно, потому что там много размеров:
- batch,
- длина последовательности,
- число голов,
- размерность головы.

# 3. Attention и архитектура моделей

В этой части:
- загрузим несколько небольших моделей,
- посмотрим конфиг,
- выясним токенайзер,
- узнаем число слоев, голов и размерность,
- предскажем размеры attention-тензоров,
- найдем матрицы проекций,
- визуализируем attention.

## 3.1. Смотрим конфиги моделей
"""

model_names = [
    'distilbert-base-uncased',
    'gpt2',
    'google/mt5-small',
]

for name in model_names:
    cfg = AutoConfig.from_pretrained(name)
    print('=' * 80)
    print(name)
    print(cfg)
    print()

from transformers import AutoModel, AutoModelForCausalLM, AutoModelForSeq2SeqLM

models_to_print = [
    ("distilbert-base-uncased", "encoder"),
    ("gpt2", "causal_lm"),
    ("google/mt5-small", "seq2seq"),
]

for name, kind in models_to_print:
    print("=" * 100)
    print(name)

    if kind == "encoder":
        model = AutoModel.from_pretrained(name)
    elif kind == "causal_lm":
        model = AutoModelForCausalLM.from_pretrained(name)
    elif kind == "seq2seq":
        model = AutoModelForSeq2SeqLM.from_pretrained(name)
    else:
        raise ValueError(f"Unknown kind: {kind}")

    print(model)
    print()

"""Вот базовая имплементация scaled_dot_product_attention https://docs.pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html:


def scaled_dot_product_attention(query, key, value, attn_mask=None,   dropout_p=0.0, is_causal=False, scale=None, enable_gqa=False) -> torch.Tensor:

      L, S = query.size(-2), key.size(-2)
      scale_factor = 1 / math.sqrt(query.size(-1)) if scale is None else scale
      attn_bias = torch.zeros(L, S, dtype=query.dtype, device=query.device)
      if is_causal:
          assert attn_mask is None
          temp_mask = torch.ones(L, S, dtype=torch.bool).tril(diagonal=0)
          attn_bias.masked_fill_(temp_mask.logical_not(), float("-inf"))

      if attn_mask is not None:
          if attn_mask.dtype == torch.bool:
              attn_bias.masked_fill_(attn_mask.logical_not(), float("-inf"))
          else:
              attn_bias = attn_mask + attn_bias

      if enable_gqa:
          key = key.repeat_interleave(query.size(-3)//key.size(-3), -3)
          value = value.repeat_interleave(query.size(-3)//value.size(-3), -3)

      attn_weight = query @ key.transpose(-2, -1) * scale_factor
      attn_weight += attn_bias
      attn_weight = torch.softmax(attn_weight, dim=-1)
      attn_weight = torch.dropout(attn_weight, dropout_p, train=True)
      return attn_weight @ value

### К сведению: вот так выглядит слой MT5DenseGatedActDense https://github.com/huggingface/transformers/blob/main/src/transformers/models/mt5/modeling_mt5.py

class MT5DenseGatedActDense(nn.Module):

    def __init__(self, config: MT5Config):
        super().__init__()
        self.wi_0 = nn.Linear(config.d_model, config.d_ff, bias=False)
        self.wi_1 = nn.Linear(config.d_model, config.d_ff, bias=False)
        self.wo = nn.Linear(config.d_ff, config.d_model, bias=False)
        self.dropout = nn.Dropout(config.dropout_rate)
        self.act = ACT2FN[config.dense_act_fn]

    def forward(self, hidden_states):
        hidden_gelu = self.act(self.wi_0(hidden_states))
        hidden_linear = self.wi_1(hidden_states)
        hidden_states = hidden_gelu * hidden_linear
        hidden_states = self.dropout(hidden_states)

        # To make 8bit quantization work for google/flan-t5-xxl, self.wo is kept in float32.
        # See https://github.com/huggingface/transformers/issues/20287
        # we also make sure the weights are not in `int8` in case users will force `_keep_in_fp32_modules` to be `None``
        if (
            isinstance(self.wo.weight, torch.Tensor)
            and hidden_states.dtype != self.wo.weight.dtype
            and self.wo.weight.dtype != torch.int8
        ):
            hidden_states = hidden_states.to(self.wo.weight.dtype)

        hidden_states = self.wo(hidden_states)
        return hidden_states

## 3.2. Вытаскиваем ключевые параметры
"""

def extract_basic_params(cfg):
    hidden = getattr(cfg, 'hidden_size', None)
    if hidden is None:
        hidden = getattr(cfg, 'd_model', None)

    heads = getattr(cfg, 'num_attention_heads', None)
    if heads is None:
        heads = getattr(cfg, 'num_heads', None)

    layers = getattr(cfg, 'num_hidden_layers', None)
    if layers is None:
        layers = getattr(cfg, 'num_layers', None)
    if layers is None:
        layers = getattr(cfg, 'encoder_layers', None)

    return hidden, heads, layers

for name in model_names:
    cfg = AutoConfig.from_pretrained(name)
    hidden, heads, layers = extract_basic_params(cfg)
    print(f'{name:30s} hidden={hidden}, heads={heads}, layers={layers}')

"""## 3.3. Предсказание размеров

Пусть:
- batch size = `B`
- seq len = `T`
- hidden size = `d_model`
- num heads = `h`
- head dim = `d_k = d_model / h`

Тогда обычно:

\[
X \in \mathbb{R}^{B \times T \times d_{model}}
\]

\[
Q, K, V \in \mathbb{R}^{B \times h \times T \times d_k}
\]

\[
QK^\top \in \mathbb{R}^{B \times h \times T \times T}
\]

То есть attention matrix для каждой головы имеет размер `T x T`.

"""

B = 2
T = 7
d_model = 768
h = 12
d_k = d_model // h

print('X      :', (B, T, d_model))
print('Q, K, V:', (B, h, T, d_k))
print('Scores :', (B, h, T, T))

"""## 3.4. Распечатываем модель и ищем attention-блоки"""

model_name = 'distilbert-base-uncased'
tok = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

print(model)

"""## 3.5. Где искать `W_K`?

В разных моделях названия разные.

Например:
- у BERT-подобных моделей часто есть что-то вроде `attention.self.key`
- у GPT-подобных — объединенные проекции или отдельные `q_proj`, `k_proj`, `v_proj`
- у T5/mT5 — свои имена слоев.

Ниже посмотрим все параметры, в названии которых встречается `key`, `k_proj` или `c_attn`.

"""

for name, param in model.named_parameters():
    lname = name.lower()
    if ('key' in lname) or ('k_proj' in lname) or ('c_attn' in lname):
        print(name, tuple(param.shape))

"""Если хочется найти конкретный слой, можно смотреть, например, первый attention-блок и его веса."""

# Пример для DistilBERT: смотрим первый attention-модуль
first_block = model.transformer.layer[0].attention
print(first_block)

for name, param in first_block.named_parameters():
    print(name, tuple(param.shape))

"""## 3.6. Визуализация attention

Возьмем маленькую модель и короткую фразу. Для encoder-only моделей удобно смотреть self-attention.

"""

model_name = 'distilbert-base-uncased'
tok = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name, attn_implementation='eager')
model.eval()

text = 'The small dog sleeps on the carpet, and dreams about electric sheep.'
batch = tok(text, return_tensors='pt')

with torch.no_grad():
    out = model(**batch, output_attentions=True, return_dict=True)

print(type(out.attentions), len(out.attentions))
print(out.attentions[0].shape)  # (batch, heads, seq, seq)

layer = -3
head = 2

attn = out.attentions[layer][0, head].cpu().numpy()
tokens = tok.convert_ids_to_tokens(batch['input_ids'][0])

plt.figure(figsize=(7, 6))
plt.imshow(attn, aspect='auto')
plt.xticks(range(len(tokens)), tokens, rotation=45, ha='right')
plt.yticks(range(len(tokens)), tokens)
plt.title(f'Self-attention, layer={layer}, head={head}')
plt.colorbar()
plt.show()

"""## 3.7. Поиск интересных паттернов

Попробуйте:

1. Перебрать разные головы.
2. Перебрать разные слои.
3. Сравнить короткое и длинное предложение.
4. Посмотреть, есть ли головы, которые:
   - сильно смотрят на `[CLS]` или `[SEP]`,
   - имеют почти диагональный паттерн,
   - имеют вертикальные полосы,
   - выделяют пунктуацию.

"""

# Перебор нескольких голов последнего слоя
layer = -1
num_heads = out.attentions[layer].shape[1]

fig, axes = plt.subplots(1, num_heads, figsize=(3 * num_heads, 3), constrained_layout=True)

for h in range(num_heads):
    ax = axes[h]
    mat = out.attentions[layer][0, h].cpu().numpy()
    ax.imshow(mat, aspect='auto')
    ax.set_title(f'head {h}')
    ax.set_xticks(range(len(tokens)))
    ax.set_xticklabels(tokens, rotation=90, fontsize=7)
    ax.set_yticks(range(len(tokens)))
    ax.set_yticklabels(tokens, fontsize=7)

plt.show()

"""# Домашние мини-упражнения

1. Взять еще один токенайзер и сравнить его на русском и на коде.
2. Для заданных `B, T, d_model, h` вручную выписать размеры `Q, K, V` и `QK^T`.
3. Для еще одной модели из `transformers` найти число слоев, голов и размерность. Есть ли в ее механизме внимания интересные особенности?
4. Найти конкретный параметр, который соответствует `W_K`.
5. Подобрать голову attention с наиболее интересным паттерном и описать его словами.

"""